apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-report
  labels:
    app: weather-report
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-report
  template:
    metadata:
      labels:
        app: weather-report
    spec:
      containers:
      - name: weather-frontend
        image: ayush180/weather-frontend:v2
        ports:
        - containerPort: 3000

      - name: weather-backend
        image: ayush180/weather-backend:v2
        ports:
        - containerPort: 5000
